<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12629" started-at="2020-09-10T16:18:04Z" finished-at="2020-09-10T16:18:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12629" started-at="2020-09-10T16:18:04Z" finished-at="2020-09-10T16:18:17Z">
      <class name="Demo.TestNG_class">
        <test-method status="PASS" signature="a()[pri:0, instance:Demo.TestNG_class@31ef45e3]" name="a" duration-ms="8" started-at="2020-09-10T21:48:04Z" finished-at="2020-09-10T21:48:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a -->
        <test-method status="FAIL" signature="m1()[pri:0, instance:Demo.TestNG_class@31ef45e3]" name="m1" duration-ms="0" started-at="2020-09-10T21:48:04Z" finished-at="2020-09-10T21:48:04Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Demo.TestNG_class.m1(TestNG_class.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m1 -->
        <test-method status="PASS" signature="login()[pri:0, instance:Demo.TestNG_class@31ef45e3]" name="login" duration-ms="12575" started-at="2020-09-10T21:48:04Z" depends-on-methods="Demo.TestNG_class.a" finished-at="2020-09-10T21:48:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- Demo.TestNG_class -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
